[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  # Environment variables can also be set here
  # REACT_APP_GA_TRACKING_ID = "G-NBNBDSTW1N"  # Commented out - use Netlify dashboard instead

# Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"