name: Feature Request
description: Suggest an enhancement for the 54-Day Novena Tracker
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for the 54-Day Novena Tracker!
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: I'm always frustrated when...
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered
      
  - type: dropdown
    id: category
    attributes:
      label: What category does this feature fall under?
      options:
        - Prayer Experience
        - User Interface
        - Data/Progress Tracking
        - Educational Content
        - Accessibility
        - Technical/Performance
        - Other
        
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request