name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter (if available)
      run: npm run lint --if-present
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build production bundle
      run: npm run build
      
    - name: Check build size
      run: |
        echo "Build completed successfully!"
        du -sh build/
        echo "Main JS bundle size:"
        find build/static/js -name "*.js" -exec du -h {} \;